"""
Disclaimers Guardrail — Phase 5: Guardrails.

Appends required regulatory and internal disclaimers to the final brief
based on the asset classes and products mentioned in the text.
"""

# Standard footer for all briefs
STANDARD_DISCLAIMER = (
    "INTERNAL USE ONLY. This brief is generated by the Wealth Manager Copilot "
    "and must be independently verified by the Relationship Manager before "
    "any client communication. Past performance is not indicative of future results."
)

# Conditional disclaimers based on content triggers
CONDITIONAL_DISCLAIMERS = {
    "high yield": "High Yield Disclaimer: High yield bonds involve greater credit risk and volatility than investment-grade bonds.",
    "emerging market": "Emerging Markets Disclaimer: Investments in emerging markets may be subject to higher volatility and currency risk.",
    "crypto": "Digital Assets Disclaimer: Cryptocurrencies and digital assets are highly speculative, unregulated, and subject to extreme volatility.",
    "bitcoin": "Digital Assets Disclaimer: Cryptocurrencies and digital assets are highly speculative, unregulated, and subject to extreme volatility.",
    "alternative": "Alternatives Disclaimer: Alternative investments are illiquid and suitable only for sophisticated investors.",
}


def apply_disclaimers(text: str) -> str:
    """
    Scans the text for triggers and appends the relevant disclaimers.
    """
    lower_text = text.lower()
    triggered = []

    for trigger, disclaimer in CONDITIONAL_DISCLAIMERS.items():
        if trigger in lower_text and disclaimer not in triggered:
            triggered.append(disclaimer)

    # Build the footer
    footer = "\n\n---\n**DISCLAIMERS:**\n"
    footer += f"- {STANDARD_DISCLAIMER}\n"
    
    for d in triggered:
        footer += f"- {d}\n"

    return text + footer
